apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeauction-config
  namespace: kubeauction
data:
  SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/kubeauction
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  MINIO_URI: http://minio:9000
  MINIO_USER: minioadmin
  MINIO_KEY: minioadmin
