apiVersion: v1
kind: Service
metadata:
  name: kubeauction-app
  namespace: kubeauction
spec:
  selector:
    app: kubeauction
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
