apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kubeauction
spec:
  replicas: 1
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
