apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeauction-ingress
  namespace: kubeauction
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubeauction-app
                port:
                  number: 8080
    - host: minio.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
